/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 bikemodel.gltf 
Author: pallavicini.daniele (https://sketchfab.com/pallavicini.daniele)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-monobike-sketchfab-challenge-99e099663418409191f33963b77cf62e
Title: Cyberpunk - Monobike Sketchfab Challenge
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bikemodel.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.012}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 76.599, -5.246]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Monobike_Monobike_U1_0.geometry} material={materials.Monobike_U1} />
            <mesh geometry={nodes.Monobike_Monobike_U2_0.geometry} material={materials.Monobike_U2} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bikemodel.gltf')
